import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import { QueryProvider } from "./components/QueryProvider";

import "./styles/global.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={plusJakartaSans.className}>
            <body>
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
